ALTER TABLE DMQUAI
ADD HINHANH text;

ALTER TABLE DMSUON
ADD HINHANH text;

ALTER TABLE DMGIAY
ADD HINHANH text;

ALTER TABLE DMGOT
ADD HINHANH text;


-- ALTER TABLE DONHANG
-- ADD SIZE1 int NOT NULL DEFAULT 0;

-- ALTER TABLE PHANCONG
-- ADD SIZE1 int NOT NULL DEFAULT 0;

-- ALTER TABLE CONGNO
-- ADD SIZE1 int NOT NULL DEFAULT 0;