USE [PT]
GO
/****** Object:  Table [dbo].[DMMAU]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DMMAU](
	[MAMAU] [varchar](20) NOT NULL,
	[TENMAU] [varchar](250) NULL,
	[GHICHU] [varchar](250) NULL,
 CONSTRAINT [PK_DMMAU] PRIMARY KEY CLUSTERED 
(
	[MAMAU] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DMGOT]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DMGOT](
	[MAGOT] [varchar](20) NOT NULL,
	[TENGOT] [varchar](250) NULL,
	[MAMAU] [varchar](20) NULL,
	[GHICHU] [varchar](250) NULL,
	[HANH] [varchar](255) NULL,
 CONSTRAINT [PK_DMGOT] PRIMARY KEY CLUSTERED 
(
	[MAGOT] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DMMUI]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DMMUI](
	[MAMUI] [varchar](20) NOT NULL,
	[TENMUI] [varchar](250) NULL,
	[MAMAU] [varchar](20) NULL,
	[GHICHU] [varchar](250) NULL,
 CONSTRAINT [PK_DMMUI] PRIMARY KEY CLUSTERED 
(
	[MAMUI] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DMSUON]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DMSUON](
	[MASUON] [varchar](20) NOT NULL,
	[TENSUON] [varchar](250) NULL,
	[MAGOT] [varchar](20) NULL,
	[MAMUI] [varchar](20) NULL,
	[GHICHU] [varchar](250) NULL,
	[HANH] [varchar](255) NULL,
 CONSTRAINT [PK_DMSUON] PRIMARY KEY CLUSTERED 
(
	[MASUON] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DMQUAI]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DMQUAI](
	[MAQUAI] [varchar](20) NOT NULL,
	[TENQUAI] [varchar](250) NULL,
	[GHICHU] [varchar](250) NULL,
	[DONGIA] [money] NULL,
	[HANH] [varchar](255) NULL,
 CONSTRAINT [PK_DMQUAI] PRIMARY KEY CLUSTERED 
(
	[MAQUAI] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DMKHACHHANG]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DMKHACHHANG](
	[MAKH] [varchar](20) NOT NULL,
	[TENKH] [varchar](250) NULL,
	[DIACHI] [varchar](500) NULL,
	[TEL] [varchar](150) NULL,
	[FAX] [varchar](150) NULL,
	[EMAIL] [varchar](250) NULL,
	[GHICHU] [varchar](250) NULL,
	[DONGIA] [money] NULL,
 CONSTRAINT [PK_DMKHACHHANG] PRIMARY KEY CLUSTERED 
(
	[MAKH] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DMCA]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DMCA](
	[MACA] [varchar](20) NOT NULL,
	[TENCA] [varchar](250) NULL,
	[MAMUI] [varchar](20) NULL,
	[MAMAU] [varchar](20) NULL,
	[GHICHU] [varchar](250) NULL,
 CONSTRAINT [PK_DMCA] PRIMARY KEY CLUSTERED 
(
	[MACA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DMDE]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DMDE](
	[MADE] [varchar](20) NOT NULL,
	[TENDE] [varchar](250) NULL,
	[MAMAU] [varchar](20) NULL,
	[GHICHU] [varchar](250) NULL,
	[DONGIA] [money] NULL,
 CONSTRAINT [PK_DMDE] PRIMARY KEY CLUSTERED 
(
	[MADE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DMGIAY]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DMGIAY](
	[MAGIAY] [varchar](30) NOT NULL,
	[TENGIAY] [varchar](250) NULL,
	[MADE] [varchar](20) NULL,
	[MASUON] [varchar](20) NULL,
	[MACA] [varchar](20) NULL,
	[MAQUAI] [varchar](20) NULL,
	[GHICHU] [varchar](250) NULL,
	[HANH] [varchar](255) NULL,
	[DONGIA] [money] NULL,
	[MAMAU] [varchar](20) NULL,
	[MAKH] [varchar](20) NULL,
	[SortID] [varchar](20) NULL,
	[GIATRANGTRI] [money] NULL,
	[GIASUON] [money] NULL,
	[GIAGOT] [money] NULL,
	[GIATANTRANG] [money] NULL,
	[GIANHANCONG] [money] NULL,
	[GIAKEO] [money] NULL,
	[TRANGTRIDE] [varchar](500) NULL,
	[GHICHUDE] [varchar](500) NULL,
	[TRANGTRIQUAI] [varchar](500) NULL,
	[GHICHUQUAI] [varchar](500) NULL,
 CONSTRAINT [PK_DMGIAY] PRIMARY KEY CLUSTERED 
(
	[MAGIAY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  View [dbo].[V_GIAY]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   VIEW [dbo].[V_GIAY] AS
SELECT 	DMGIAY. MAGIAY, DMGIAY.TENGIAY, DMGIAY.MADE, DMGIAY.MASUON, 
	DMGIAY.MACA, DMGIAY.MAQUAI, DMGIAY.DONGIA,
	DMQUAI.TENQUAI, DMDE.TENDE, DMCA.TENCA, SUON.TENSUON, SUON.MAGOT, 
	SUON.TENGOT, SUON.MAMUI, SUON.TENMUI,
	DMQUAI.DONGIA AS DONGIAQUAI, DMDE.DONGIA AS DONGIADE,
	DMGIAY.MAKH, DMKHACHHANG.TENKH, DMGIAY.SORTID, DMGIAY.TRANGTRIDE,
	DMGIAY.TRANGTRIQUAI, DMGIAY.GHICHUDE, DMGIAY.GHICHUQUAI
FROM DMGIAY
LEFT JOIN DMQUAI ON DMQUAI.MAQUAI = DMGIAY.MAQUAI
LEFT JOIN DMDE ON DMDE.MADE = DMGIAY.MADE
LEFT JOIN DMCA ON DMCA.MACA = DMGIAY.MACA
LEFT JOIN DMKHACHHANG ON DMGIAY.MAKH = DMKHACHHANG.MAKH
LEFT JOIN (SELECT 	S1.MASUON, S1.TENSUON, S1.MAGOT, S1.MAMUI,
			G1.TENGOT, M1.TENMUI 
	   FROM DMSUON AS S1 	LEFT JOIN DMGOT AS G1 ON S1.MAGOT = G1.MAGOT
				LEFT JOIN DMMUI AS M1 ON S1.MAMUI = M1.MAMUI) AS SUON ON SUON.MASUON = DMGIAY.MASUON
GO
/****** Object:  Table [dbo].[PHANCONG]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PHANCONG](
	[MADONG] [varchar](20) NOT NULL,
	[MAPHIEU] [varchar](20) NOT NULL,
	[SOPHIEU] [varchar](20) NULL,
	[NGAYPHIEU] [datetime] NULL,
	[DIENGIAIPHIEU] [varchar](250) NULL,
	[SODH] [varchar](20) NULL,
	[MAGIAY] [varchar](30) NULL,
	[SIZE5] [money] NULL,
	[SIZE6] [money] NULL,
	[SIZE7] [money] NULL,
	[SIZE8] [money] NULL,
	[SIZE9] [money] NULL,
	[THODE] [varchar](20) NULL,
	[THOQUAI] [varchar](20) NULL,
	[DAIN] [int] NULL,
	[DIENGIAIDONG] [varchar](250) NULL,
	[NGAYTAO] [datetime] NULL,
	[NGUOITAO] [varchar](20) NULL,
	[NGUOISUA] [varchar](20) NULL,
	[NGAYSUA] [datetime] NULL,
	[MAUDE] [varchar](20) NULL,
	[MAUGOT] [varchar](20) NULL,
	[MAUSUON] [varchar](20) NULL,
	[MAUCA] [varchar](20) NULL,
	[MAUQUAI] [varchar](20) NULL,
	[Size0] [float] NULL,
	[MAKY] [varchar](20) NULL,
 CONSTRAINT [PK_PHANCONG] PRIMARY KEY CLUSTERED 
(
	[MADONG] ASC,
	[MAPHIEU] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CHAMCONG]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CHAMCONG](
	[MAKY] [varchar](20) NULL,
	[MANVIEN] [varchar](20) NULL,
	[MAGIAY] [varchar](30) NULL,
	[SOLUONG] [int] NULL,
	[DONGIA] [money] NULL,
	[THANHTIEN] [money] NULL,
	[madong] [varchar](20) NOT NULL,
	[maphieu] [varchar](20) NOT NULL,
	[phieupc] [varchar](20) NULL,
	[maude] [varchar](20) NULL,
	[maugot] [varchar](20) NULL,
	[mausuon] [varchar](20) NULL,
	[mauca] [varchar](20) NULL,
	[mauquai] [varchar](20) NULL,
	[NgayPhieu] [datetime] NULL,
	[DienGiai] [varchar](250) NULL,
 CONSTRAINT [PK_CHAMCONG] PRIMARY KEY CLUSTERED 
(
	[madong] ASC,
	[maphieu] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DMNHANVIEN]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DMNHANVIEN](
	[MANVIEN] [varchar](20) NOT NULL,
	[TENNVIEN] [varchar](250) NULL,
	[LOAINVIEN] [varchar](20) NULL,
	[MATKHAU] [varchar](250) NULL,
	[GHICHU] [varchar](250) NULL,
 CONSTRAINT [PK_DMNHANVIEN] PRIMARY KEY CLUSTERED 
(
	[MANVIEN] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  View [dbo].[V_TK_TEMP1]    Script Date: 04/29/2023 11:37:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE View [dbo].[V_TK_TEMP1]  As  
SELECT 
G.MAKH, 
G.TENKH, 
SUM(PC.SIZE5 + PC.SIZE6 + PC.SIZE7 + PC.SIZE8 + PC.SIZE9 + PC.SIZE0, PC.SIZE1) AS SLGIAOVIEC,
0 AS SLGIAOHANG, 
0 AS TONGTIEN
FROM PHANCONG PC LEFT JOIN V_GIAY G ON PC.MAGIAY = G.MAGIAY
WHERE PC.MAKY = '02'
GROUP BY G.MAKH, G.TENKH 
UNION ALL
SELECT 
G.MAKH, 
G.TENKH, 
0 AS SLGIAOVIEC,
SUM(CC.SOLUONG) AS SLGIAOHANG,
SUM(CC.SOLUONG * G.DONGIA) AS TONGTIEN
FROM CHAMCONG CC LEFT JOIN V_GIAY G ON CC.MAGIAY = G.MAGIAY
		 Left Join DMNHANVIEN On DMNHANVIEN.MANVIEN=CC.MANVIEN
WHERE CC.MAKY = '02' AND DMNHANVIEN.LOAINVIEN = 'TD'
GROUP BY G.MAKH, G.TENKH
GO
/****** Object:  View [dbo].[V_TONGKET]    Script Date: 04/29/2023 11:37:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE View [dbo].[V_TONGKET]  As  
SELECT MAKH, TENKH, 
SUM(SLGIAOVIEC) AS SLGIAOVIEC,
SUM(SLGIAOHANG) AS SLGIAOHANG,
SUM(TONGTIEN) AS TONGTIEN 
FROM V_TK_TEMP1 GROUP BY MAKH, TENKH
GO
/****** Object:  Table [dbo].[DMKYTINHLUONG]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DMKYTINHLUONG](
	[MAKY] [varchar](20) NOT NULL,
	[TENKY] [varchar](255) NULL,
	[TUNGAY] [datetime] NULL,
	[DENNGAY] [datetime] NULL,
 CONSTRAINT [PK_DMKYTINHLUONG] PRIMARY KEY CLUSTERED 
(
	[MAKY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  View [dbo].[V_CHAMCONG]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE     VIEW [dbo].[V_CHAMCONG] AS 
Select  CHAMCONG.PHIEUPC, CHAMCONG.MaKy, CHAMCONG.MaGiay,CHAMCONG.MANVIEN,
	(SELECT TOP 1 DIENGIAIPHIEU FROM PHANCONG WHERE PHANCONG.SOPHIEU = CHAMCONG.PHIEUPC)AS DIENGIAIPHIEU, 
	 SUM(CHAMCONG.SOLUONG) AS SOLUONG,
	CASE WHEN DMNHANVIEN.LOAINVIEN = 'TD' THEN V_GIAY.DONGIADE ELSE V_GIAY.DONGIAQUAI END AS DONGIA,
	DMKYTINHLUONG.TENKY,V_GIAY.TENGIAY,DMNHANVIEN.TENNVIEN, DMNHANVIEN.LOAINVIEN as MALOAINV,
	CASE 	WHEN DMNHANVIEN.LOAINVIEN = 'TD' THEN 'THOI ÑEA' 
		WHEN DMNHANVIEN.LOAINVIEN = 'TQ' THEN 'THOI QUAI' ELSE 'KHAUC' END AS LOAINV,
	CASE 	WHEN DMNHANVIEN.LOAINVIEN = 'TD' THEN V_GIAY.MADE ELSE '' END AS MADE,
	CASE	WHEN DMNHANVIEN.LOAINVIEN = 'TQ' THEN V_GIAY.MAQUAI ELSE '' END AS MAQUAI
From CHAMCONG 	Left Join DMKYTINHLUONG On DMKYTINHLUONG.MAKY=CHAMCONG.MAKY 
		Left Join V_GIAY On V_GIAY.MAGIAY=CHAMCONG.MAGIAY 
		Left Join DMNHANVIEN On DMNHANVIEN.MANVIEN=CHAMCONG.MANVIEN
GROUP BY CHAMCONG.PHIEUPC, CHAMCONG.MaKy, CHAMCONG.MaGiay, 
CHAMCONG.MANVIEN, DMKYTINHLUONG.TENKY,V_GIAY.TENGIAY,DMNHANVIEN.TENNVIEN, 
DMNHANVIEN.LOAINVIEN, V_GIAY.DONGIADE, V_GIAY.DONGIAQUAI, V_GIAY.MAQUAI, V_GIAY.MADE
GO
/****** Object:  View [dbo].[V_TKLUONGQUAI]    Script Date: 04/29/2023 11:37:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE View [dbo].[V_TKLUONGQUAI]  As  
SELECT 
MANVIEN, TENNVIEN,
SUM(SOLUONG) AS SOLUONG,
SUM(SOLUONG*DONGIA) AS TONGLUONG 
FROM V_CHAMCONG
WHERE MAKY = '02' AND MALOAINV = 'TQ'
GROUP BY MANVIEN, TENNVIEN
GO
/****** Object:  View [dbo].[V_TKLUONGDE]    Script Date: 04/29/2023 11:37:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE View [dbo].[V_TKLUONGDE]  As  
SELECT 
MANVIEN, TENNVIEN,
SUM(SOLUONG) AS SOLUONG,
SUM(SOLUONG*DONGIA) AS TONGLUONG 
FROM V_CHAMCONG
WHERE MAKY = '02' AND MALOAINV = 'TD'
GROUP BY MANVIEN, TENNVIEN
GO
/****** Object:  Table [dbo].[PHANQUYEN]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PHANQUYEN](
	[MANVIEN] [varchar](20) NOT NULL,
	[MAFORM] [varchar](20) NOT NULL,
	[TENFORM] [varchar](250) NULL,
	[THEM] [int] NULL,
	[SUA] [int] NULL,
	[XOA] [int] NULL,
	[XEM] [int] NULL,
	[IN] [int] NULL,
 CONSTRAINT [PK_PHANQUYEN] PRIMARY KEY CLUSTERED 
(
	[MANVIEN] ASC,
	[MAFORM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DAPLUON]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DAPLUON](
	[SOPHIEU] [varchar](20) NOT NULL,
	[NGAYPHIEU] [varchar](20) NULL,
	[SODH] [varchar](20) NOT NULL,
	[DAIN] [tinyint] NULL,
 CONSTRAINT [PK_DAPLUON] PRIMARY KEY CLUSTERED 
(
	[SOPHIEU] ASC,
	[SODH] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CONGNO]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONGNO](
	[MADONG] [varchar](20) NOT NULL,
	[MAPHIEU] [varchar](20) NOT NULL,
	[SOPHIEU] [varchar](20) NULL,
	[DIENGIAIPHIEU] [varchar](250) NULL,
	[LOAIPHIEU] [varchar](20) NULL,
	[MAKH] [varchar](20) NULL,
	[NGAYPHIEU] [datetime] NULL,
	[MAGIAY] [varchar](30) NULL,
	[SOLUONG] [money] NULL,
	[GIABAN] [money] NULL,
	[THANHTIEN] [money] NULL,
	[DIENGIAIDONG] [varchar](250) NULL,
	[NGUOITAO] [varchar](20) NULL,
	[NGAYTAO] [datetime] NULL,
	[NGUOISUA] [varchar](20) NULL,
	[NGAYSUA] [datetime] NULL,
	[SODH] [varchar](50) NULL,
	[SIZE5] [float] NULL,
	[SIZE6] [float] NULL,
	[SIZE7] [float] NULL,
	[SIZE8] [float] NULL,
	[SIZE9] [float] NULL,
	[MAUDE] [varchar](50) NULL,
	[MAUGOT] [varchar](50) NULL,
	[MAUSUON] [varchar](50) NULL,
	[MAUCA] [varchar](50) NULL,
	[MAUQUAI] [varchar](50) NULL,
	[Size0] [float] NULL,
 CONSTRAINT [PK_CONGNO] PRIMARY KEY CLUSTERED 
(
	[MAPHIEU] ASC,
	[MADONG] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  StoredProcedure [dbo].[P_TONGKET]    Script Date: 04/29/2023 11:37:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE         PROCEDURE [dbo].[P_TONGKET]
					@MAKY as varchar(20),
					@FromDate as datetime,
					@ToDate as datetime
AS
BEGIN
Declare  @sSQL as varchar(8000)
SET @sSQL = ' 
SELECT 
G.MAKH, 
G.TENKH, 
SUM(PC.SIZE5 + PC.SIZE6 + PC.SIZE7 + PC.SIZE8 + PC.SIZE9 + PC.SIZE0 + PC.SIZE1) AS SLGIAOVIEC,
0 AS SLGIAOHANG, 
0 AS TONGTIEN
FROM PHANCONG PC LEFT JOIN V_GIAY G ON PC.MAGIAY = G.MAGIAY
WHERE PC.MAKY = '''+@MAKY+'''
GROUP BY G.MAKH, G.TENKH 
UNION ALL
SELECT 
G.MAKH, 
G.TENKH, 
0 AS SLGIAOVIEC,
SUM(CC.SOLUONG) AS SLGIAOHANG,
SUM(CC.SOLUONG * G.DONGIA) AS TONGTIEN
FROM CHAMCONG CC LEFT JOIN V_GIAY G ON CC.MAGIAY = G.MAGIAY
		 Left Join DMNHANVIEN On DMNHANVIEN.MANVIEN=CC.MANVIEN
WHERE CC.MAKY = '''+@MAKY+''' AND DMNHANVIEN.LOAINVIEN = ''TD''
GROUP BY G.MAKH, G.TENKH'
If not exists (Select name from sysobjects Where id = Object_id(N'[dbo].[V_TK_TEMP1]') and OBJECTPROPERTY(id, N'IsView') = 1)
    Exec ('  Create View V_TK_TEMP1 as ' + @sSQL)
Else
    Exec ('  Alter View V_TK_TEMP1  As ' + @sSQL)
PRINT @sSQL
SET @sSQL = ' 
SELECT MAKH, TENKH, 
SUM(SLGIAOVIEC) AS SLGIAOVIEC,
SUM(SLGIAOHANG) AS SLGIAOHANG,
SUM(TONGTIEN) AS TONGTIEN 
FROM V_TK_TEMP1 GROUP BY MAKH, TENKH '
If not exists (Select name from sysobjects Where id = Object_id(N'[dbo].[V_TONGKET]') and OBJECTPROPERTY(id, N'IsView') = 1)
    Exec ('  Create View V_TONGKET as ' + @sSQL)
Else
    Exec ('  Alter View V_TONGKET  As ' + @sSQL)
-- tao view in tong ket luong tho de
SET @sSQL = ' 
SELECT 
MANVIEN, TENNVIEN,
SUM(SOLUONG) AS SOLUONG,
SUM(SOLUONG*DONGIA) AS TONGLUONG 
FROM V_CHAMCONG
WHERE MAKY = '''+@MAKY+''' AND MALOAINV = ''TQ''
GROUP BY MANVIEN, TENNVIEN
'
If not exists (Select name from sysobjects Where id = Object_id(N'[dbo].[V_TKLUONGQUAI]') and OBJECTPROPERTY(id, N'IsView') = 1)
    Exec ('  Create View V_TKLUONGQUAI as ' + @sSQL)
Else
    Exec ('  Alter View V_TKLUONGQUAI  As ' + @sSQL)
SET @sSQL = ' 
SELECT 
MANVIEN, TENNVIEN,
SUM(SOLUONG) AS SOLUONG,
SUM(SOLUONG*DONGIA) AS TONGLUONG 
FROM V_CHAMCONG
WHERE MAKY = '''+@MAKY+''' AND MALOAINV = ''TD''
GROUP BY MANVIEN, TENNVIEN
'
If not exists (Select name from sysobjects Where id = Object_id(N'[dbo].[V_TKLUONGDE]') and OBJECTPROPERTY(id, N'IsView') = 1)
    Exec ('  Create View V_TKLUONGDE as ' + @sSQL)
Else
    Exec ('  Alter View V_TKLUONGDE  As ' + @sSQL)
--PRINT @sSQL
END
GO
/****** Object:  Table [dbo].[EXCEL]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[EXCEL](
	[MaHang] [varchar](20) NOT NULL,
	[BarCode] [varchar](20) NULL,
	[TenHang] [varchar](50) NULL,
	[Gia] [money] NULL,
	[SLIN] [money] NULL,
	[GhiChu] [varchar](250) NULL,
	[Diengiai] [varchar](500) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DONHANG]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DONHANG](
	[MADONG] [varchar](20) NOT NULL,
	[MADH] [varchar](20) NOT NULL,
	[SODH] [varchar](20) NULL,
	[MAKH] [varchar](20) NULL,
	[NGAYDH] [datetime] NULL,
	[NGAYGH] [datetime] NULL,
	[DIENGIAIPHIEU] [varchar](250) NULL,
	[MAGIAY] [varchar](30) NULL,
	[SIZE5] [float] NULL,
	[SIZE6] [float] NULL,
	[SIZE7] [float] NULL,
	[SIZE9] [float] NULL,
	[SIZE8] [float] NULL,
	[GIABAN] [money] NULL,
	[THANHTIEN] [money] NULL,
	[DIENGIAIDONG] [varchar](250) NULL,
	[NGUOITAO] [varchar](20) NULL,
	[NGAYTAO] [datetime] NULL,
	[NGUOISUA] [varchar](20) NULL,
	[NGAYSUA] [datetime] NULL,
	[MAUDE] [varchar](20) NULL,
	[MAUGOT] [varchar](20) NULL,
	[MAUSUON] [varchar](20) NULL,
	[MAUCA] [varchar](20) NULL,
	[MAUQUAI] [varchar](20) NULL,
	[DAPHANCONG] [float] NULL,
	[Size0] [float] NULL,
	[GIALE] [float] NULL,
	[tmpField] [float] NULL,
	[tmpField1] [float] NULL,
	[INHIEU] [varchar](50) NULL,
	[TRANGTRI] [varchar](500) NULL,
	[GHICHU] [varchar](500) NULL,
 CONSTRAINT [PK_DONHANG] PRIMARY KEY CLUSTERED 
(
	[MADONG] ASC,
	[MADH] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DMKHO]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DMKHO](
	[MAKHO] [varchar](20) NOT NULL,
	[TENKHO] [varchar](250) NULL,
	[GHICHU] [varchar](250) NULL,
 CONSTRAINT [PK_DMKHO] PRIMARY KEY CLUSTERED 
(
	[MAKHO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** Object:  StoredProcedure [dbo].[P_CONGNOTONGHOP]    Script Date: 04/29/2023 11:37:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[P_CONGNOTONGHOP]
					@FromDate as datetime,
					@ToDate as datetime,
					@FromMAKH as varchar(30),
					@ToMAKH as varchar(30)
AS
Declare  @sSQL as varchar(8000)
BEGIN
--CONG NO TONG HOP
set @sSQL=   ' SELECT MAKH, TENKH,
               SUM (CASE WHEN NgayPhieu < '''+convert(varchar(10),@FromDate,101)+''' THEN THANHTIENQD ELSE 0 END)  AS SODUDAU,
               ABS(SUM (CASE WHEN 	NgayPhieu >= '''+convert(varchar(10),@FromDate,101)+''' and NgayPhieu <= '''+convert(varchar(10),@ToDate,101)+''' AND (IsNull(DC,'''') = ''D'' ) THEN THANHTIENQD ELSE 0 END)) AS PHATSINHTANG,
               ABS(SUM (CASE WHEN 	NgayPhieu >= '''+convert(varchar(10),@FromDate,101)+''' and NgayPhieu <= '''+convert(varchar(10),@ToDate,101)+''' AND (IsNull(DC,'''') = ''C'' ) THEN THANHTIENQD ELSE 0 END)) AS PHATSINHGIAM,
               SUM (CASE WHEN NgayPhieu <= '''+convert(varchar(10),@ToDate,101)+''' THEN THANHTIENQD ELSE 0 END)  AS SODUCUOI
               FROM V_TONGHOP 
	       WHERE MAKH >= '''+@FromMAKH+''' AND MAKH <= '''+@ToMAKH+'''
               GROUP BY MAKH, TENKH'
If not exists (Select name from sysobjects Where id = Object_id(N'[dbo].[V_CNTONGHOP]') and OBJECTPROPERTY(id, N'IsView') = 1)
    Exec ('  Create View V_CNTONGHOP as ' + @sSQL)
Else
    Exec ('  Alter View V_CNTONGHOP  As ' + @sSQL)
--CONG NO CHI TIET
set @sSQL=   ' SELECT V_TONGHOP.*, V_CNTONGHOP.SODUDAU, V_CNTONGHOP.SODUCUOI
               FROM V_TONGHOP LEFT JOIN V_CNTONGHOP ON V_TONGHOP.MAKH = V_CNTONGHOP.MAKH 
	       WHERE V_TONGHOP.MAKH >= '''+@FromMAKH+''' AND V_TONGHOP.MAKH <= '''+@ToMAKH+''' AND 
		V_TONGHOP.NgayPhieu >= '''+convert(varchar(10),@FromDate,101)+''' and V_TONGHOP.NgayPhieu <= '''+convert(varchar(10),@ToDate,101)+''''
If not exists (Select name from sysobjects Where id = Object_id(N'[dbo].[V_CNCHITIET]') and OBJECTPROPERTY(id, N'IsView') = 1)
    Exec ('  Create View V_CNCHITIET as ' + @sSQL)
Else
    Exec ('  Alter View V_CNCHITIET  As ' + @sSQL)
--PRINT @sSQL
END
GO
/****** Object:  Table [dbo].[V1T8000]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[V1T8000](
	[SectionID] [varchar](20) NOT NULL,
	[IsShow] [tinyint] NOT NULL,
	[Section] [varchar](50) NULL,
	[FontDetail] [varchar](250) NULL,
	[FontName] [varchar](50) NOT NULL,
	[FontSize] [tinyint] NOT NULL,
	[FontType] [varchar](50) NOT NULL,
	[Content] [varchar](100) NULL,
	[Alignment] [tinyint] NOT NULL,
	[IsLock] [tinyint] NOT NULL,
	[IsHide] [tinyint] NOT NULL,
	[PrintGridLine] [tinyint] NOT NULL,
	[TopMargin] [float] NOT NULL,
	[BottomMargin] [float] NOT NULL,
	[LeftMargin] [float] NOT NULL,
	[RightMargin] [float] NOT NULL,
	[Path] [varchar](250) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[V1T4444]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[V1T4444](
	[TABLENAME] [char](8) NULL,
	[KEYSTRING] [varchar](20) NULL,
	[LASTKEY] [int] NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[V1T1101]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[V1T1101](
	[DivisionID] [varchar](20) NOT NULL,
	[DivisionName] [varchar](250) NULL,
	[Disabled] [bit] NOT NULL,
	[Tel] [varchar](50) NULL,
	[Fax] [varchar](50) NULL,
	[Email] [varchar](100) NULL,
	[Address] [varchar](250) NULL,
	[ContactPerson] [varchar](50) NULL,
	[VATNO] [varchar](50) NULL,
	[BeginMonth] [int] NULL,
	[BeginYear] [int] NULL,
	[CreateDate] [datetime] NULL,
	[CreateUserID] [varchar](20) NULL,
	[LastModifyDate] [datetime] NULL,
	[LastModifyUserID] [varchar](20) NULL,
	[SoGPDT] [varchar](20) NULL,
	[NgayCap] [datetime] NULL,
	[LoaiHinhDN] [varchar](50) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/****** Object:  StoredProcedure [dbo].[V1P0000]    Script Date: 04/29/2023 11:37:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-------- Created by Hoang Manh Hung.
--------  Created Date 20.08.2003
------- Purpose: Automatic create New ID keys
CREATE PROCEDURE [dbo].[V1P0000]  @NewKey varchar(20) OUTPUT, 
				    @TableName  char(8),
				    @StringKey1 varchar(20) ='', 
				    @StringKey2 varchar(20) ='',
				    @StringKey3 varchar(20)='', 
				    @OutputLen int = 10, 
				    @OutputOrder int = 3, 	   	--- 0 NSSS; 1 SNSS, 2 SSNS, 3 SSSN
				    @Seperated int =0, 
				    @Seperator char(1) ='-'  AS
Declare @KeyString varchar(20),
	@LastKey int,
	@LastKeyChar varchar(20),
	@LastKeyLen int,
	@SeperatorCount int,
	@KeyStringLen int,
	@StringNumber varchar(20),
	@Seperator1 varchar (1),
	@Seperator2 varchar (1),
	@Seperator3 varchar (1)
SET NOCOUNT ON
select @KeyString = @StringKey1 + @StringKey2 + @StringKey3
if exists (select  LastKey  from V1T4444 where TableName = @TableName and KeyString = @KeyString)
	begin
		select @LastKey  =LastKey + 1 
		from  V1T4444 
		where TableName = @TableName and KeyString = @KeyString	
		update  V1T4444 set LastKey = @LastKey where TableName = @TableName and KeyString = @KeyString	
		
	end
else
	begin
		insert into  V1T4444 (TableName, KeyString, LastKey) VALUES (@TableName, @KeyString, 1)
		select @LastKey = 1	
	end
select @LastKeyChar = LTRIM(STR(@LastKey))
select @LastKeyLen  = LEN(@LastKeyChar)
if @Seperated = 0
begin
	select @SeperatorCount = 0
	select @Seperator =SPACE(0)
end
else
begin
	select @SeperatorCount = 0
	if LEN(@StringKey1) > 0 
		begin
			select @SeperatorCount = 1
			select @Seperator1 = @Seperator
		end
	else
		begin
			select @Seperator1 = SPACE(0)
		end
	if LEN(@StringKey2) > 0 
		begin
			select @SeperatorCount = @SeperatorCount + 1
			select @Seperator2 = @Seperator
	             end
	else
		begin
			select @Seperator2 = SPACE(0)
		end
	if LEN(@StringKey3) > 0 
		begin
			select @SeperatorCount = @SeperatorCount + 1
			select @Seperator3 = @Seperator
		end
	else
		begin
			select @Seperator3 = SPACE(0)
		end
end
select @StringNumber =   REPLICATE('0', @OutputLen - @LastKeyLen - @SeperatorCount  - LEN(@KeyString))  + @LastKeyChar
select @StringKey1 = LTRIM(UPPER(@StringKey1))
select @StringKey2 = LTRIM(UPPER(@StringKey2))
select @StringKey3 = LTRIM(UPPER(@StringKey3))
	Set 	@NewKey  = 
		(CASE @OutputOrder
			WHEN 3 THEN isnull(@StringKey1,'') + isnull(@Seperator1,'') + isnull(@StringKey2,'') + isnull(@Seperator2,'') + isnull(@StringKey3,'') + isnull(@Seperator3,'') + @StringNumber
			WHEN 1 THEN @StringKey1 +  isnull(@Seperator1,'') + @StringNumber +  isnull(@Seperator2,'') + @StringKey2 +isnull(@Seperator3 ,'')+ @StringKey3 
			WHEN 2 THEN @StringKey1 + isnull(@Seperator1,'') +  @StringKey2 + isnull(@Seperator2,'') + @StringNumber  + isnull(@Seperator3,'') + @StringKey3 
			WHEN 0 THEN @StringNumber + isnull(@Seperator1,'') + @StringKey1 +  isnull(@Seperator2 ,'')+  @StringKey2 + isnull( @Seperator3,'') + @StringKey3 
		 END)
--Select @NewKey  as NewKey
SET NOCOUNT OFF
GO
/****** Object:  View [dbo].[V_CHAMCONGTHOQUAI]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE VIEW [dbo].[V_CHAMCONGTHOQUAI] AS
SELECT 
	dmgiay.tengiay,PC.SOPHIEU, PC.MAGIAY,  pc.maude,PC.MAUGOT, PC.MAUSUON, PC.MAUCA, PC.MAUQUAI,pc.THOQUAI,
	SUM(PC.SIZE5 + PC.SIZE6 + PC.SIZE7 + PC.SIZE8  +PC.SIZE9 +PC.SIZE0+PC.SIZE1) AS SLPHANCONG, 
	ISNULL((SELECT SUM(ISNULL(CC.SOLUONG,0))  FROM CHAMCONG CC  WHERE PC.SOPHIEU = CC.PHIEUPC AND 
								PC.MAGIAY = CC.MAGIAY AND 
								PC.MAUGOT = CC.MAUGOT AND 
								PC.MAUSUON = CC.MAUSUON AND 
								PC.MAUCA = CC.MAUCA AND 
								PC.mauquai = CC.mauquai and 
								pc.maude=cc.maude and 
								pc.THOQUAI=cc.manvien),0) AS SLCHAMCONG, 
	
	(SUM(PC.SIZE5 + PC.SIZE6 + PC.SIZE7 + PC.SIZE8  +PC.SIZE9+PC.SIZE0+PC.SIZE1 ) - 
	
	ISNULL((SELECT SUM(ISNULL(CC.SOLUONG,0))  FROM CHAMCONG CC  WHERE PC.SOPHIEU = CC.PHIEUPC AND 
								PC.MAGIAY = CC.MAGIAY AND 
								PC.MAUGOT = CC.MAUGOT AND 
								PC.MAUSUON = CC.MAUSUON AND 
								PC.MAUCA = CC.MAUCA AND 
								PC.mauquai = CC.mauquai and 
								pc.maude=cc.maude and 
								pc.THOQUAI=cc.manvien),0)) AS SLCONLAI 
FROM PHANCONG PC 
			left join dmgiay on dmgiay.magiay=pc.magiay 
GROUP BY tengiay,PC.SOPHIEU, PC.MAGIAY,  pc.maude,PC.MAUGOT, PC.MAUSUON, PC.MAUCA, PC.MAUQUAI ,pc.THOQUAI
GO

/****** Object:  View [dbo].[V_DHPHANCONG]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE  VIEW [dbo].[V_DHPHANCONG] AS 
SELECT DISTINCT dh.madh,dh.sodh,dh.ngaydh,dh.makh,dh.diengiaiphieu,kh.tenkh,
	ISNULL(SUM(DH.SIZE5 + DH.SIZE6 + DH.SIZE7 + DH.SIZE8  +DH.SIZE9 +DH.SIZE0+DH.SIZE1),0) AS SLDONHANG,
	ISNULL((SELECT SUM(PC.SIZE5 + PC.SIZE6 + PC.SIZE7 + PC.SIZE8  + PC.SIZE9 + PC.SIZE0 + PC.SIZE1) FROM PHANCONG PC WHERE DH.SODH = PC.SODH),0) AS SLPHANCONG
FROM DONHANG DH Left Join DMkhachhang kh on kh.makh=dh.makh 
GROUP BY dh.madh,dh.sodh,dh.ngaydh,dh.makh,kh.tenkh,dh.diengiaiphieu
GO
/****** Object:  View [dbo].[V_DHGIAOHANG]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE VIEW [dbo].[V_DHGIAOHANG] AS 
SELECT DISTINCT dh.sodh,dh.ngaydh,dh.ngaygh,dh.makh,kh.tenkh,dh.diengiaiphieu AS DIENGIAI,dh.madh, dh.tmpfield as dagh,
	ISNULL(SUM(DH.SIZE5 + DH.SIZE6 + DH.SIZE7 + DH.SIZE8  +DH.SIZE9  +DH.SIZE0+DH.SIZE1),0) AS SLDONHANG,
	ISNULL((SELECT SUM(CN.SIZE5 + CN.SIZE6 + CN.SIZE7 + CN.SIZE8  +CN.SIZE9 +CN.SIZE0+CN.SIZE1) FROM CONGNO CN WHERE DH.SODH = CN.SODH),0) AS SLGIAOHANG
FROM DONHANG DH Left Join DMkhachhang kh on kh.makh=dh.makh 
GROUP BY dh.sodh,dh.makh,kh.tenkh,dh.diengiaiphieu,madh,dh.ngaydh,dh.ngaygh,dh.tmpfield
GO
/****** Object:  Table [dbo].[NHAPXUAT]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[NHAPXUAT](
	[MADONG] [varchar](20) NOT NULL,
	[MAPHIEU] [varchar](20) NOT NULL,
	[LOAIPHIEU] [varchar](20) NULL,
	[SOPHIEU] [varchar](20) NULL,
	[MAKHO] [varchar](20) NULL,
	[NGAYPHIEU] [datetime] NULL,
	[DIENGIAIPHIEU] [varchar](20) NULL,
	[MAHANG] [varchar](20) NULL,
	[SOLUONG] [money] NULL,
	[NGUOITAO] [varchar](20) NULL,
	[NGAYTAO] [datetime] NULL,
	[NGUOISUA] [varchar](20) NULL,
	[NGAYSUA] [datetime] NULL,
	[DIENGIAIDONG] [varchar](250) NULL,
 CONSTRAINT [PK_NHAPXUAT] PRIMARY KEY CLUSTERED 
(
	[MAPHIEU] ASC,
	[MADONG] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  View [dbo].[V_TKTONGHOP]    Script Date: 04/29/2023 11:37:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create View [dbo].[V_TKTONGHOP] as
Select MAKHO, MAHANG, DMGOT.TENGOT,
SUM(Case  When LoaiPhieu = 'PN'Then SoLuong Else 0 End) as TongNhap,
SUM(Case  When LoaiPhieu = 'PX'Then SoLuong Else 0 End) as TongXuat,
(SUM(Case  When LoaiPhieu = 'PX'Then SoLuong Else 0 End) - SUM(Case  
When LoaiPhieu = 'PN'Then SoLuong Else 0 End)) as Ton
From NHAPXUAT Left Join DMGOT on NHAPXUAT.MAHANG = DMGOT.MAGOT
Group By MAKHO, MAHANG, DMGOT.TENGOT
GO
/****** Object:  View [dbo].[V_NHAPKHO]    Script Date: 04/29/2023 11:37:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create View [dbo].[V_NHAPKHO] as
Select NHAPXUAT.*,DMGOT.TENGOT, DMKHO.TENKHO From NHAPXUAT Left Join 
DMKHO On DMKHO.MAKHO=NHAPXUAT.MAKHO Left Join DMGOT On 
DMGOT.MAGOT=NHAPXUAT.MAHANG
GO
/****** Object:  View [dbo].[V_PHANCONGTH]    Script Date: 04/29/2023 11:37:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create view [dbo].[V_PHANCONGTH] as 
Select 	PHANCONG.*, V_GIAY.TENGIAY ,DMMAUGOT.TENMAU as TENMAUGOT, 
	V_GIAY.MADE, V_GIAY.MAGOT, 
	V_GIAY.MASUON, V_GIAY.MACA, V_GIAY.MAQUAI, 
	V_GIAY.TENCA,	
	DMMAUDE.TENMAU as TENMAUDE,
	DMMAUSUON.TENMAU as TENMAUSUON,
	DMMAUQUAI.TENMAU as TENMAUQUAI,
	DMMAUCA.TENMAU as TENMAUCA, DH.MAKH,V_GIAY.DONGIA,
	DMTHODE.TENNVIEN AS TENTHODE,
	DMTHOQUAI.TENNVIEN AS TENTHOQUAI,
	V_GIAY.DONGIADE,
	V_GIAY.DONGIAQUAI
From PHANCONG  
	Left Join V_GIAY On V_GIAY.MAGIAY=PHANCONG.MAGIAY
	Left Join DMMAU as DMMAUGOT On DMMAUGOT.MAMAU=PHANCONG.MAUGOT
	Left Join DMMAU as DMMAUDE On DMMAUDE.MAMAU=PHANCONG.MAUDE
	Left Join DMMAU as DMMAUSUON On DMMAUSUON.MAMAU=PHANCONG.MAUSUON
	Left Join DMMAU as DMMAUQUAI On DMMAUQUAI.MAMAU=PHANCONG.MAUQUAI
	Left Join DMMAU as DMMAUCA On DMMAUCA.MAMAU=PHANCONG.MAUCA
	Left Join (Select Distinct SODH, MAKH, NGAYDH FROM DONHANG)AS DH On DH.SODH=PHANCONG.SODH
	Left Join DMNHANVIEN AS DMTHODE On DMTHODE.MANVIEN=PHANCONG.THODE
	Left Join DMNHANVIEN AS DMTHOQUAI On DMTHOQUAI.MANVIEN=PHANCONG.THOQUAI
GO
/****** Object:  View [dbo].[V_PHANCONG]    Script Date: 04/29/2023 11:37:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--SELECT * FROM DMNHANVIEN
--dROP VIEW V_PHANCONG
CREATE      view [dbo].[V_PHANCONG] as
Select 	PHANCONG.THOQUAI AS MATHO, PHANCONG.*, V_GIAY.TENGIAY ,DMMAUGOT.TENMAU as TENMAUGOT, V_GIAY.MADE, V_GIAY.MAGOT, 
	V_GIAY.MASUON, V_GIAY.MACA, V_GIAY.MAQUAI, V_GIAY.TENCA,	
	DMMAUDE.TENMAU as TENMAUDE,
	DMMAUSUON.TENMAU as TENMAUSUON,
	DMMAUQUAI.TENMAU as TENMAUQUAI,
	DMMAUCA.TENMAU as TENMAUCA, DH.MAKH,V_GIAY.DONGIA,
	DMTHODE.TENNVIEN AS TENTHODE,
	DMTHOQUAI.TENNVIEN AS TENTHOQUAI,
	V_GIAY.DONGIADE,
	V_GIAY.DONGIAQUAI
From PHANCONG  
	Left Join V_GIAY On V_GIAY.MAGIAY=PHANCONG.MAGIAY
	Left Join DMMAU as DMMAUGOT On DMMAUGOT.MAMAU=PHANCONG.MAUGOT
	Left Join DMMAU as DMMAUDE On DMMAUDE.MAMAU=PHANCONG.MAUDE
	Left Join DMMAU as DMMAUSUON On DMMAUSUON.MAMAU=PHANCONG.MAUSUON
	Left Join DMMAU as DMMAUQUAI On DMMAUQUAI.MAMAU=PHANCONG.MAUQUAI
	Left Join DMMAU as DMMAUCA On DMMAUCA.MAMAU=PHANCONG.MAUCA
	Left Join (Select Distinct SODH, MAKH, NGAYDH FROM DONHANG)AS DH On DH.SODH=PHANCONG.SODH
	Left Join DMNHANVIEN AS DMTHODE On DMTHODE.MANVIEN=PHANCONG.THODE
	Left Join DMNHANVIEN AS DMTHOQUAI On DMTHOQUAI.MANVIEN=PHANCONG.THOQUAI
UNION ALL
Select 	PHANCONG.THODE AS MATHO, PHANCONG.*, V_GIAY.TENGIAY ,DMMAUGOT.TENMAU as TENMAUGOT, V_GIAY.MADE, V_GIAY.MAGOT, 
	V_GIAY.MASUON, V_GIAY.MACA, V_GIAY.MAQUAI,V_GIAY.TENCA,
	DMMAUDE.TENMAU as TENMAUDE,
	DMMAUSUON.TENMAU as TENMAUSUON,
	DMMAUQUAI.TENMAU as TENMAUQUAI,
	DMMAUCA.TENMAU as TENMAUCA, DH.MAKH,V_GIAY.DONGIA,
	DMTHODE.TENNVIEN AS TENTHODE,
	DMTHOQUAI.TENNVIEN AS TENTHOQUAI,
	V_GIAY.DONGIADE,
	V_GIAY.DONGIAQUAI
From PHANCONG  
	Left Join V_GIAY On V_GIAY.MAGIAY=PHANCONG.MAGIAY
	Left Join DMMAU as DMMAUGOT On DMMAUGOT.MAMAU=PHANCONG.MAUGOT
	Left Join DMMAU as DMMAUDE On DMMAUDE.MAMAU=PHANCONG.MAUDE
	Left Join DMMAU as DMMAUSUON On DMMAUSUON.MAMAU=PHANCONG.MAUSUON
	Left Join DMMAU as DMMAUQUAI On DMMAUQUAI.MAMAU=PHANCONG.MAUQUAI
	Left Join DMMAU as DMMAUCA On DMMAUCA.MAMAU=PHANCONG.MAUCA
	Left Join (Select Distinct SODH, MAKH, NGAYDH FROM DONHANG)AS DH On DH.SODH=PHANCONG.SODH
	Left Join DMNHANVIEN AS DMTHODE On DMTHODE.MANVIEN=PHANCONG.THODE
	Left Join DMNHANVIEN AS DMTHOQUAI On DMTHOQUAI.MANVIEN=PHANCONG.THOQUAI
GO
/****** Object:  View [dbo].[V_KQPHANCONG]    Script Date: 04/29/2023 11:37:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
--SP_HELPTEXT V_GIAY
CREATE   VIEW [dbo].[V_KQPHANCONG] AS
SELECT PHANCONG.*,
NV01.TENNVIEN TENTHODE,
NV02.TENNVIEN TENTHOQUAI,
(size5 + size6 + size7 + size8 + size9+ size0) as TONGSL,
(size5 + size6 + size7 + size8 + size9+ size0)*DONGIAQUAI as LUONGQUAI, 
(size5 + size6 + size7 + size8 + size9+ size0)*DONGIADE as LUONGDE
FROM PHANCONG 	LEFT JOIN V_GIAY ON PHANCONG.MAGIAY = V_GIAY.MAGIAY
		LEFT JOIN DMNHANVIEN NV01 ON PHANCONG.THODE = NV01.MANVIEN
		LEFT JOIN DMNHANVIEN NV02 ON PHANCONG.THOQUAI = NV02.MANVIEN
GO
/****** Object:  View [dbo].[V_CHAMCONGKH]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[V_CHAMCONGKH]
AS
SELECT     dbo.V_GIAY.MAKH, dbo.V_GIAY.TENKH, dbo.CHAMCONG.MAGIAY, dbo.V_GIAY.TENGIAY, dbo.CHAMCONG.MAKY, SUM(dbo.CHAMCONG.SOLUONG) 
                      AS SOLUONG, dbo.V_GIAY.DONGIA AS DONGIABAN
FROM         dbo.CHAMCONG LEFT OUTER JOIN
                      dbo.DMNHANVIEN ON dbo.DMNHANVIEN.MANVIEN = dbo.CHAMCONG.MANVIEN LEFT OUTER JOIN
                      dbo.V_GIAY ON dbo.V_GIAY.MAGIAY = dbo.CHAMCONG.MAGIAY
WHERE     (dbo.DMNHANVIEN.LOAINVIEN = 'TD')
GROUP BY dbo.V_GIAY.MAKH, dbo.V_GIAY.TENKH, dbo.CHAMCONG.MAGIAY, dbo.V_GIAY.TENGIAY, dbo.V_GIAY.DONGIA, dbo.CHAMCONG.MAKY
GO
/****** Object:  View [dbo].[V_DONHANG]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE    view [dbo].[V_DONHANG] as
Select DONHANG.SODH,  DONHANG.MAKH,  DONHANG.NGAYDH,  DONHANG.NGAYGH,   
DONHANG.DIENGIAIPHIEU,  DONHANG.MAUQUAI,
DONHANG.SIZE5,  DONHANG.SIZE6,  DONHANG.SIZE7,  DONHANG.SIZE8,  
DONHANG.SIZE9,   DONHANG.GIABAN, 
DONHANG.SIZE0, DONHANG.SIZE1, 
DONHANG.THANHTIEN,  DONHANG.NGUOITAO,  DONHANG.NGUOISUA,
V_GIAY.MAGIAY, V_GIAY.TENGIAY, V_GIAY.MADE, V_GIAY.MASUON, V_GIAY.MACA, V_GIAY.MAQUAI, V_GIAY.DONGIA,
V_GIAY.TENQUAI, V_GIAY.TENDE, V_GIAY.TENCA, V_GIAY.TENSUON, V_GIAY.MAGOT, V_GIAY.TENGOT, 
V_GIAY.MAMUI, V_GIAY.TENMUI, V_GIAY.DONGIAQUAI, V_GIAY.DONGIADE, V_GIAY.TRANGTRIDE, V_GIAY.TRANGTRIQUAI,
V_GIAY.GHICHUDE, V_GIAY.GHICHUQUAI,
DMMAUGOT.TENMAU as TENMAUGOT,
DMMAUDE.TENMAU as TENMAUDE,
DMMAUSUON.TENMAU as TENMAUSUON,
DMMAUQUAI.TENMAU as TENMAUQUAI,
DMMAUCA.TENMAU as TENMAUCA,
DMKHACHHANG.TENKH, DMKHACHHANG.DIACHI, DONHANG.INHIEU, DONHANG.TRANGTRI, DONHANG.GHICHU
From DONHANG 
Left Join V_GIAY On V_GIAY.MAGIAY=DONHANG.MAGIAY
Left Join DMMAU as DMMAUGOT On DMMAUGOT.MAMAU=DONHANG.MAUGOT
Left Join DMMAU as DMMAUDE On DMMAUDE.MAMAU=DONHANG.MAUDE
Left Join DMMAU as DMMAUSUON On DMMAUSUON.MAMAU=DONHANG.MAUSUON
Left Join DMMAU as DMMAUQUAI On DMMAUQUAI.MAMAU=DONHANG.MAUQUAI
Left Join DMMAU as DMMAUCA On DMMAUCA.MAMAU=DONHANG.MAUCA
Left Join DMKHACHHANG On DMKHACHHANG.MAKH=DONHANG.MAKH
GO
/****** Object:  View [dbo].[V_BCDONHANG]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE VIEW [dbo].[V_BCDONHANG] AS
SELECT 	SODH, DH.MAKH, KH.TENKH, NGAYDH, NGAYGH, 
	DIENGIAIPHIEU, DH.MAGIAY, V_GIAY.TENGIAY,
	SIZE5, SIZE6, SIZE7, SIZE9, SIZE8, SIZE0, SIZE1,
	GIABAN, THANHTIEN, DIENGIAIDONG, 
	MAUDE ,MAUGOT, MAUSUON, MAUCA, MAUQUAI
FROM 	DONHANG DH
		LEFT JOIN V_GIAY ON V_GIAY.MAGIAY = DH.MAGIAY
		LEFT JOIN DMMAU MAUDE ON MAUDE.MAMAU = DH.MAUDE
		LEFT JOIN DMMAU MAUGOT ON MAUGOT.MAMAU = DH.MAUGOT
		LEFT JOIN DMMAU MAUSUON ON MAUSUON.MAMAU = DH.MAUSUON
		LEFT JOIN DMMAU MAUCA ON MAUCA.MAMAU = DH.MAUCA
		LEFT JOIN DMMAU MAUQUAI ON MAUQUAI.MAMAU = DH.MAUQUAI
		LEFT JOIN DMKHACHHANG KH ON KH.MAKH = DH.MAKH
GO
/****** Object:  View [dbo].[V_TONGHOP]    Script Date: 04/29/2023 11:37:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[V_TONGHOP] AS
SELECT 	CN.SOPHIEU, CN.DIENGIAIPHIEU, CN.LOAIPHIEU, CN.NGAYPHIEU, CN.MAGIAY,
	CN.SOLUONG, CN.GIABAN, CN.SODH, CN.MAKH, KH.TENKH, V_GIAY.TENGIAY,
	CN.THANHTIEN AS THANHTIENQD,
	'D' AS DC
FROM CONGNO CN 	LEFT JOIN DMKHACHHANG KH ON CN.MAKH = KH.MAKH
		LEFT JOIN V_GIAY ON CN.MAGIAY = V_GIAY.MAGIAY
WHERE CN.LOAIPHIEU = 'BH'
UNION ALL
SELECT 	CN.SOPHIEU, CN.DIENGIAIPHIEU, CN.LOAIPHIEU, CN.NGAYPHIEU, CN.MAGIAY,
	CN.SOLUONG, CN.GIABAN, CN.SODH, CN.MAKH, KH.TENKH, V_GIAY.TENGIAY,
	CN.THANHTIEN*(-1) AS THANHTIENQD,
	'C' AS DC
FROM CONGNO CN 	LEFT JOIN DMKHACHHANG KH ON CN.MAKH = KH.MAKH
		LEFT JOIN V_GIAY ON CN.MAGIAY = V_GIAY.MAGIAY
WHERE CN.LOAIPHIEU = 'PT'
GO
/****** Object:  View [dbo].[V_GIAYTHEOKH]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE     view [dbo].[V_GIAYTHEOKH] as
Select distinct 	sortid,V_GIAY.magiay,V_GIAY.tengiay,maude,maugot, 
			mausuon,mauca,mauquai ,donhang.makh, 
			V_GIAY.DONGIA, V_GIAY.DONGIAQUAI, V_GIAY.TENCA, V_GIAY.TENKH
from donhang 
	left join V_GIAY on V_GIAY.magiay=donhang.magiay
GO

/****** Object:  View [dbo].[V_CNTONGHOP]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE View [dbo].[V_CNTONGHOP]  As  SELECT MAKH, TENKH,
               SUM (CASE WHEN NgayPhieu < '04/28/2023' THEN THANHTIENQD ELSE 0 END)  AS SODUDAU,
               ABS(SUM (CASE WHEN 	NgayPhieu >= '04/28/2023' and NgayPhieu <= '04/28/2023' AND (IsNull(DC,'') = 'D' ) THEN THANHTIENQD ELSE 0 END)) AS PHATSINHTANG,
               ABS(SUM (CASE WHEN 	NgayPhieu >= '04/28/2023' and NgayPhieu <= '04/28/2023' AND (IsNull(DC,'') = 'C' ) THEN THANHTIENQD ELSE 0 END)) AS PHATSINHGIAM,
               SUM (CASE WHEN NgayPhieu <= '04/28/2023' THEN THANHTIENQD ELSE 0 END)  AS SODUCUOI
               FROM V_TONGHOP 
	       WHERE MAKH >= 'THU' AND MAKH <= 'THU'
               GROUP BY MAKH, TENKH
GO

/****** Object:  View [dbo].[V_GIAOHANG]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[V_GIAOHANG] AS SELECT dbo.CONGNO.MAPHIEU, dbo.CONGNO.SODH, dbo.CONGNO.MAGIAY, dbo.CONGNO.SOPHIEU, dbo.CONGNO.NGAYPHIEU, dbo.CONGNO.DIENGIAIPHIEU, dbo.CONGNO.MAKH, SUM(dbo.CONGNO.SOLUONG) AS SOLUONG, dbo.CONGNO.GIABAN, SUM(dbo.CONGNO.THANHTIEN) AS THANHTIEN, dbo.DMKHACHHANG.TENKH, dbo.DMGIAY.TENGIAY, dbo.DMKHACHHANG.DIACHI, dbo.V_CNTONGHOP.SODUCUOI, dbo.V_CNTONGHOP.SODUDAU FROM dbo.CONGNO LEFT OUTER JOIN dbo.DMGIAY ON dbo.DMGIAY.MAGIAY = dbo.CONGNO.MAGIAY LEFT OUTER JOIN dbo.DMKHACHHANG ON dbo.DMKHACHHANG.MAKH = dbo.CONGNO.MAKH LEFT OUTER JOIN dbo.V_CNTONGHOP ON dbo.V_CNTONGHOP.MAKH = dbo.CONGNO.MAKH GROUP BY dbo.CONGNO.MAPHIEU, dbo.CONGNO.SODH, dbo.CONGNO.GIABAN, dbo.CONGNO.THANHTIEN, dbo.DMKHACHHANG.TENKH, dbo.DMGIAY.TENGIAY, dbo.DMKHACHHANG.DIACHI, dbo.V_CNTONGHOP.SODUCUOI, dbo.CONGNO.SOPHIEU, dbo.CONGNO.MAGIAY, dbo.CONGNO.NGAYPHIEU, dbo.CONGNO.DIENGIAIPHIEU, dbo.CONGNO.MAKH, dbo.V_CNTONGHOP.SODUDAU
GO
/****** Object:  View [dbo].[V_CNCHITIET]    Script Date: 04/29/2023 11:37:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE View [dbo].[V_CNCHITIET]  As  SELECT V_TONGHOP.*, V_CNTONGHOP.SODUDAU, V_CNTONGHOP.SODUCUOI
               FROM V_TONGHOP LEFT JOIN V_CNTONGHOP ON V_TONGHOP.MAKH = V_CNTONGHOP.MAKH 
	       WHERE V_TONGHOP.MAKH >= 'THU' AND V_TONGHOP.MAKH <= 'THU' AND 
		V_TONGHOP.NgayPhieu >= '04/28/2023' and V_TONGHOP.NgayPhieu <= '04/28/2023'
GO
/****** Object:  StoredProcedure [dbo].[P_EXCEL]    Script Date: 04/29/2023 11:37:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE  PROCEDURE [dbo].[P_EXCEL]
AS
declare @strAutoNumber as varchar(20),
        @strBarCode as varchar(20),
        @Number as int,
        @Excel_Cur as Cursor,
        @Tenhang as varchar(50),
	@DIENGIAI AS VARCHAR(500)
BEGIN
     Set @Excel_Cur = CURSOR SCROLL KEYSET FOR
                 SELECT MAGIAY, TENGIAY FROM V_EXCEL WHERE MAGIAY IS NOT NULL
     OPEN @Excel_Cur
     Fetch Next From @Excel_Cur into @Tenhang, @DIENGIAI
     While @@FETCH_STATUS = 0
     BEGIN
          IF NOT EXISTS (SELECT TOP 1 1 FROM EXCEL WHERE Tenhang = ISNULL(@Tenhang,''))
          BEGIN
          Exec V1P0000  @strAutoNumber  OUTPUT, 'EXCEL', '', '', '', 12, 3, 0, ''
          Set @Number = 	  10 -(((Cast(SubString(@strAutoNumber,12,1) as int) +
		              	     Cast(SubString(@strAutoNumber,10,1) as int) +
                      		 Cast(SubString(@strAutoNumber,8,1) as int) +
                             Cast(SubString(@strAutoNumber,6,1) as int) +
                             Cast(SubString(@strAutoNumber,4,1) as int) +
			                 Cast(SubString(@strAutoNumber,2,1) as int)) *3 +
        		             (Cast(SubString(@strAutoNumber,11,1) as int)+
			                 Cast(SubString(@strAutoNumber,9,1) as int)+
			                 Cast(SubString(@strAutoNumber,7,1) as int)+
			                 Cast(SubString(@strAutoNumber,5,1) as int)+
			                 Cast(SubString(@strAutoNumber,3,1) as int)+
			                 Cast(SubString(@strAutoNumber,1,1) as int)))%10)
          Set @strBarCode = @strAutoNumber + Right(str(@Number),1)
          INSERT INTO EXCEL (MaHang, BarCode, TenHang, Gia, SLIN, GhiChu, DIENGIAI) VALUES (@strAutoNumber, @strBarCode, @Tenhang, 0, 0, 'GIAOY P&T',@DIENGIAI)
--                             Print @strBarCode
         END
     Fetch Next From @Excel_Cur into @Tenhang, @DIENGIAI
     END
     CLOSE @Excel_Cur
END
GO
/****** Object:  Default [DF__congno__Size0__540C7B00]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[CONGNO] ADD  CONSTRAINT [DF__congno__Size0__540C7B00]  DEFAULT (0) FOR [Size0]
GO
/****** Object:  Default [DF_DAPLUON_DAIN]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[DAPLUON] ADD  CONSTRAINT [DF_DAPLUON_DAIN]  DEFAULT (0) FOR [DAIN]
GO
/****** Object:  Default [DF__DMGIAY__GIATRANG__308E3499]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[DMGIAY] ADD  CONSTRAINT [DF__DMGIAY__GIATRANG__308E3499]  DEFAULT (0) FOR [GIATRANGTRI]
GO
/****** Object:  Default [DF__DMGIAY__GIASUON__318258D2]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[DMGIAY] ADD  CONSTRAINT [DF__DMGIAY__GIASUON__318258D2]  DEFAULT (0) FOR [GIASUON]
GO
/****** Object:  Default [DF__DMGIAY__GIAGOT__32767D0B]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[DMGIAY] ADD  CONSTRAINT [DF__DMGIAY__GIAGOT__32767D0B]  DEFAULT (0) FOR [GIAGOT]
GO
/****** Object:  Default [DF__DMGIAY__GIATANTR__336AA144]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[DMGIAY] ADD  CONSTRAINT [DF__DMGIAY__GIATANTR__336AA144]  DEFAULT (0) FOR [GIATANTRANG]
GO
/****** Object:  Default [DF__DMGIAY__GIANHANC__345EC57D]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[DMGIAY] ADD  CONSTRAINT [DF__DMGIAY__GIANHANC__345EC57D]  DEFAULT (0) FOR [GIANHANCONG]
GO
/****** Object:  Default [DF__DMGIAY__GIAKEO__3552E9B6]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[DMGIAY] ADD  CONSTRAINT [DF__DMGIAY__GIAKEO__3552E9B6]  DEFAULT (0) FOR [GIAKEO]
GO
/****** Object:  Default [DF_DMNHANVIEN_MATKHAU]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[DMNHANVIEN] ADD  CONSTRAINT [DF_DMNHANVIEN_MATKHAU]  DEFAULT ('') FOR [MATKHAU]
GO
/****** Object:  Default [DF_DONHANG_DAPHANCONG]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[DONHANG] ADD  CONSTRAINT [DF_DONHANG_DAPHANCONG]  DEFAULT (0) FOR [DAPHANCONG]
GO
/****** Object:  Default [DF__donhang__Size0__531856C7]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[DONHANG] ADD  CONSTRAINT [DF__donhang__Size0__531856C7]  DEFAULT (0) FOR [Size0]
GO
/****** Object:  Default [DF__donhang__GIALE__55F4C372]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[DONHANG] ADD  CONSTRAINT [DF__donhang__GIALE__55F4C372]  DEFAULT (0) FOR [GIALE]
GO
/****** Object:  Default [DF__donhang__tmpFiel__56E8E7AB]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[DONHANG] ADD  CONSTRAINT [DF__donhang__tmpFiel__56E8E7AB]  DEFAULT (0) FOR [tmpField]
GO
/****** Object:  Default [DF__donhang__tmpFiel__57DD0BE4]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[DONHANG] ADD  CONSTRAINT [DF__donhang__tmpFiel__57DD0BE4]  DEFAULT (0) FOR [tmpField1]
GO
/****** Object:  Default [DF__phancong__Size0__55009F39]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[PHANCONG] ADD  CONSTRAINT [DF__phancong__Size0__55009F39]  DEFAULT (0) FOR [Size0]
GO
/****** Object:  Default [DF_PHANQUYEN_THEM]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[PHANQUYEN] ADD  CONSTRAINT [DF_PHANQUYEN_THEM]  DEFAULT (0) FOR [THEM]
GO
/****** Object:  Default [DF_PHANQUYEN_SUA]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[PHANQUYEN] ADD  CONSTRAINT [DF_PHANQUYEN_SUA]  DEFAULT (0) FOR [SUA]
GO
/****** Object:  Default [DF_PHANQUYEN_XOA]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[PHANQUYEN] ADD  CONSTRAINT [DF_PHANQUYEN_XOA]  DEFAULT (0) FOR [XOA]
GO
/****** Object:  Default [DF_PHANQUYEN_XEM]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[PHANQUYEN] ADD  CONSTRAINT [DF_PHANQUYEN_XEM]  DEFAULT (0) FOR [XEM]
GO
/****** Object:  Default [DF_PHANQUYEN_IN]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[PHANQUYEN] ADD  CONSTRAINT [DF_PHANQUYEN_IN]  DEFAULT (0) FOR [IN]
GO
/****** Object:  ForeignKey [FK_DMGOT_DMMAU1]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[DMGOT]  WITH CHECK ADD  CONSTRAINT [FK_DMGOT_DMMAU1] FOREIGN KEY([MAMAU])
REFERENCES [dbo].[DMMAU] ([MAMAU])
GO
ALTER TABLE [dbo].[DMGOT] CHECK CONSTRAINT [FK_DMGOT_DMMAU1]
GO
/****** Object:  ForeignKey [FK_DMSUON_DMGOT]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[DMSUON]  WITH NOCHECK ADD  CONSTRAINT [FK_DMSUON_DMGOT] FOREIGN KEY([MAGOT])
REFERENCES [dbo].[DMGOT] ([MAGOT])
GO
ALTER TABLE [dbo].[DMSUON] NOCHECK CONSTRAINT [FK_DMSUON_DMGOT]
GO
/****** Object:  ForeignKey [FK_DMSUON_DMMUI]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[DMSUON]  WITH NOCHECK ADD  CONSTRAINT [FK_DMSUON_DMMUI] FOREIGN KEY([MAMUI])
REFERENCES [dbo].[DMMUI] ([MAMUI])
GO
ALTER TABLE [dbo].[DMSUON] NOCHECK CONSTRAINT [FK_DMSUON_DMMUI]
GO
/****** Object:  ForeignKey [FK_NHAPXUAT_DMGOT]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[NHAPXUAT]  WITH NOCHECK ADD  CONSTRAINT [FK_NHAPXUAT_DMGOT] FOREIGN KEY([MAHANG])
REFERENCES [dbo].[DMGOT] ([MAGOT])
GO
ALTER TABLE [dbo].[NHAPXUAT] NOCHECK CONSTRAINT [FK_NHAPXUAT_DMGOT]
GO
/****** Object:  ForeignKey [FK_NHAPXUAT_DMKHO]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[NHAPXUAT]  WITH NOCHECK ADD  CONSTRAINT [FK_NHAPXUAT_DMKHO] FOREIGN KEY([MAKHO])
REFERENCES [dbo].[DMKHO] ([MAKHO])
GO
ALTER TABLE [dbo].[NHAPXUAT] NOCHECK CONSTRAINT [FK_NHAPXUAT_DMKHO]
GO
/****** Object:  ForeignKey [FK_PHANQUYEN_DMNHANVIEN]    Script Date: 04/29/2023 11:37:20 ******/
ALTER TABLE [dbo].[PHANQUYEN]  WITH NOCHECK ADD  CONSTRAINT [FK_PHANQUYEN_DMNHANVIEN] FOREIGN KEY([MANVIEN])
REFERENCES [dbo].[DMNHANVIEN] ([MANVIEN])
GO
ALTER TABLE [dbo].[PHANQUYEN] NOCHECK CONSTRAINT [FK_PHANQUYEN_DMNHANVIEN]
GO
