USE [PTMain]
GO
/****** Object:  View [dbo].[V_GIAY]    Script Date: 04/29/2023 11:39:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   VIEW [dbo].[V_GIAY] AS
SELECT 	DMGIAY. MAGIAY, DMGIAY.TENGIAY, DMGIAY.MADE, DMGIAY.MASUON, 
	DMGIAY.MACA, DMGIAY.MAQUAI, DMGIAY.DONGIA,
	DMQUAI.TENQUAI, DMDE.TENDE, DMCA.TENCA, SUON.TENSUON, SUON.MAGOT, 
	SUON.TENGOT, SUON.MAMUI, SUON.TENMUI,
	DMQUAI.DONGIA AS DONGIAQUAI, DMDE.DONGIA AS DONGIADE,
	DMGIAY.MAKH, DMKHACHHANG.TENKH, DMGIAY.SORTID, DMGIAY.TRANGTRIDE,
	DMGIAY.TRANGTRIQUAI, DMGIAY.GHICHUDE, DMGIAY.GHICHUQUAI,
	DMGIAY.HAVEHINHANH
FROM DMGIAY
LEFT JOIN DMQUAI ON DMQUAI.MAQUAI = DMGIAY.MAQUAI
LEFT JOIN DMDE ON DMDE.MADE = DMGIAY.MADE
LEFT JOIN DMCA ON DMCA.MACA = DMGIAY.MACA
LEFT JOIN DMKHACHHANG ON DMGIAY.MAKH = DMKHACHHANG.MAKH
LEFT JOIN (SELECT 	S1.MASUON, S1.TENSUON, S1.MAGOT, S1.MAMUI,
			G1.TENGOT, M1.TENMUI 
	   FROM DMSUON AS S1 	LEFT JOIN DMGOT AS G1 ON S1.MAGOT = G1.MAGOT
				LEFT JOIN DMMUI AS M1 ON S1.MAMUI = M1.MAMUI) AS SUON ON SUON.MASUON = DMGIAY.MASUON
GO
